#!/usr/bin/env bash

set -euo pipefail
set +e

usage() {
    cat <<EOF
Usage: $(basename "$0") [KEYNAME ...]

Import SSH keys generated by \`ssh-keygen -K\` into your ~/.ssh directory.

By default, all generated \`id_*\` keys will be moved.
If one or more KEYNAMEs are given, only those and their .pub counterparts will be moved.

Options:
  -h, --help     Show this help message and exit

Examples:
  $(basename "$0")
      Moves all generated SSH keys to ~/.ssh

  $(basename "$0") id_ed25519_sk
      Moves only id_ed25519_sk and id_ed25519_sk.pub to ~/.ssh
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

temp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir')
ret_value=0

trap "popd >/dev/null; exit 1" INT
pushd "$temp_dir" >/dev/null

(trap "popd >/dev/null; exit 1" INT; ssh-keygen -K 2> err_output 1> output)

if [ $? -eq 0 ]; then
    if [ $# -eq 0 ]; then
        >&2 echo "copy all keys"
        mv -v id_* "${HOME}/.ssh"
    else
        for key in "$@"; do
            mv -v "${key}" "${HOME}/.ssh"
            mv -v "${key}.pub" "${HOME}/.ssh"
        done
    fi
else
    cat err_output
    ret_value=1
fi

popd >/dev/null
rm -rf "$temp_dir"

exit $ret_value