[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[block.theme_overrides]
idle_bg = "#e1fc11"
idle_fg = "#050622"

[[block]]
alert = 10.0
alias = "/"
block = "disk_space"
format = "{icon} {available}"
info_type = "available"
interval = 60
path = "/"
unit = "GB"
warning = 20.0

[block.theme_overrides]
idle_bg = "#1e0f39"
idle_fg = "#c34b37"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[block.theme_overrides]
idle_bg = "#c1224e"
idle_fg = "#e1fc11"

[[block]]
block = "cpu"
format = "{utilization} ({frequency})"
interval = 1

[block.theme_overrides]
idle_bg = "#07072a"
idle_fg = "#c34b37"

[[block]]
block = "load"
format = "{1m}"
interval = 1

[block.theme_overrides]
idle_bg = "#c34b37"
idle_fg = "#e1fc11"

[[block]]
block = "temperature"
good = 35
idle = 40
info = 55
inputs = ["CPU Temperature"]
warning = 60

[[block]]
block = "sound"

[block.theme_overrides]
idle_bg = "#983069"
idle_fg = "#e1fc11"

[[block]]
block = "time"
format = "%R"
interval = 60
timezone = "Europe/Berlin"

[block.theme_overrides]
idle_bg = "#050622"
idle_fg = "#c34b37"

[[block]]
block = "custom"
command = "echo '{\"state\": \"Idle\", \"text\": \"⏻\"}'"
interval = "once"
json = true
on_click = "systemctl $(echo -e 'suspend\npoweroff\nreboot' | /nix/store/r1lxj2gkv2zzx7z6awbjh3w79hqbj9p0-dmenu-5.3/bin/dmenu)"

[icons]
name = "awesome6"

[theme]
name = "dracula"
